/*
 * WeatherAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WeatherAPI.Standard;
using WeatherAPI.Standard.Utilities;


namespace WeatherAPI.Standard.Models
{
    public class Astro : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string sunrise;
        private string sunset;
        private string moonrise;
        private string moonset;

        /// <summary>
        /// Sunrise time
        /// </summary>
        [JsonProperty("sunrise")]
        public string Sunrise 
        { 
            get 
            {
                return this.sunrise; 
            } 
            set 
            {
                this.sunrise = value;
                onPropertyChanged("Sunrise");
            }
        }

        /// <summary>
        /// Sunset time
        /// </summary>
        [JsonProperty("sunset")]
        public string Sunset 
        { 
            get 
            {
                return this.sunset; 
            } 
            set 
            {
                this.sunset = value;
                onPropertyChanged("Sunset");
            }
        }

        /// <summary>
        /// Moonrise time
        /// </summary>
        [JsonProperty("moonrise")]
        public string Moonrise 
        { 
            get 
            {
                return this.moonrise; 
            } 
            set 
            {
                this.moonrise = value;
                onPropertyChanged("Moonrise");
            }
        }

        /// <summary>
        /// Moonset time
        /// </summary>
        [JsonProperty("moonset")]
        public string Moonset 
        { 
            get 
            {
                return this.moonset; 
            } 
            set 
            {
                this.moonset = value;
                onPropertyChanged("Moonset");
            }
        }
    }
} 