/*
 * WeatherAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WeatherAPI.Standard;
using WeatherAPI.Standard.Utilities;


namespace WeatherAPI.Standard.Models
{
    public class Condition : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string text;
        private string icon;
        private int? code;

        /// <summary>
        /// Weather condition text
        /// </summary>
        [JsonProperty("text")]
        public string Text 
        { 
            get 
            {
                return this.text; 
            } 
            set 
            {
                this.text = value;
                onPropertyChanged("Text");
            }
        }

        /// <summary>
        /// Weather icon url
        /// </summary>
        [JsonProperty("icon")]
        public string Icon 
        { 
            get 
            {
                return this.icon; 
            } 
            set 
            {
                this.icon = value;
                onPropertyChanged("Icon");
            }
        }

        /// <summary>
        /// Weather condition unique code.
        /// </summary>
        [JsonProperty("code")]
        public int? Code 
        { 
            get 
            {
                return this.code; 
            } 
            set 
            {
                this.code = value;
                onPropertyChanged("Code");
            }
        }
    }
} 