/*
 * WeatherAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using WeatherAPI.Standard.Controllers;
using WeatherAPI.Standard.Http.Client;
using WeatherAPI.Standard.Utilities;

namespace WeatherAPI.Standard
{
    public partial class WeatherAPIClient
    {

        /// <summary>
        /// Singleton access to APIs controller
        /// </summary>
        public APIsController APIs
        {
            get
            {
                return APIsController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public WeatherAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public WeatherAPIClient(string key)
        {
            Configuration.Key = key;
        }
        #endregion
    }
}